version: '3'
services:
  database:
    image: "postgres"
    container_name: db
    ports:
      - 9000:5432
    volumes:
      - ./database-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
  node-app:
    image: node:12.20.1
    container_name: node-app
    command: npm start
    environment:
      - NODE_ENV=development
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - database
